-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-11-18 13:51:51 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

-- USER
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;

-- ROLE
CREATE SEQUENCE ROLE_SEQ START WITH 1 INCREMENT BY 1;

-- ADDRESS
CREATE SEQUENCE ADDRESS_SEQ START WITH 1 INCREMENT BY 1;

-- TELLER
CREATE SEQUENCE TELLER_SEQ START WITH 1 INCREMENT BY 1;

-- CLIENT
CREATE SEQUENCE CLIENT_SEQ START WITH 1 INCREMENT BY 1;

-- ACCOUNT
CREATE SEQUENCE ACCOUNT_SEQ START WITH 1 INCREMENT BY 1;

-- TRANSACTION
CREATE SEQUENCE TRANSACTION_SEQ START WITH 1 INCREMENT BY 1;

-- TRANSACTION TYPE
CREATE SEQUENCE TRANSACTION_TYPE_SEQ START WITH 1 INCREMENT BY 1;

-- MESSAGE
CREATE SEQUENCE MESSAGE_SEQ START WITH 1 INCREMENT BY 1;

-- LOGIN RECORD
CREATE SEQUENCE LOGIN_SEQ START WITH 1 INCREMENT BY 1;

-- AUDIT LOG
CREATE SEQUENCE AUDIT_SEQ START WITH 1 INCREMENT BY 1;

-- DOCUMENT
CREATE SEQUENCE DOCUMENT_SEQ START WITH 1 INCREMENT BY 1;

-- BRANCH
CREATE SEQUENCE BRANCH_SEQ START WITH 1 INCREMENT BY 1;


-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-11-18 17:50:51 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Account
(
    Account_id      INTEGER  NOT NULL ,
    Account_number  VARCHAR2 (30)  NOT NULL ,
    Account_balance NUMBER  NOT NULL ,
    Account_active  CHAR (1)  NOT NULL ,
    Client_id       INTEGER  NOT NULL
)
;

ALTER TABLE Account
    ADD CONSTRAINT Account_PK PRIMARY KEY ( Account_id ) ;

CREATE TABLE Address
(
    Address_id   INTEGER  NOT NULL ,
    Country      VARCHAR2 (50)  NOT NULL ,
    State        VARCHAR2 (30) ,
    City         VARCHAR2 (50)  NOT NULL ,
    Street       VARCHAR2 (30)  NOT NULL ,
    House_number INTEGER  NOT NULL ,
    ZIP_code     INTEGER  NOT NULL
)
;

ALTER TABLE Address
    ADD CONSTRAINT Address_PK PRIMARY KEY ( Address_id ) ;

CREATE TABLE Audit_log
(
    Audit_id    INTEGER  NOT NULL ,
    Change_type VARCHAR2 (100)  NOT NULL ,
    Change_time DATE  NOT NULL ,
    User_id     INTEGER  NOT NULL
)
;

ALTER TABLE Audit_log
    ADD CONSTRAINT Audit_log_PK PRIMARY KEY ( Audit_id ) ;

CREATE TABLE Branch
(
    Branch_id   INTEGER  NOT NULL ,
    Branch_name VARCHAR2 (50)  NOT NULL ,
    Address_id  INTEGER  NOT NULL
)
;

ALTER TABLE Branch
    ADD CONSTRAINT Branch_PK PRIMARY KEY ( Branch_id ) ;

CREATE TABLE Client
(
    User_id       INTEGER  NOT NULL ,
    Birth_number  VARCHAR2 (20)  NOT NULL ,
    Phone_number  VARCHAR2 (15)  NOT NULL ,
    Email_address VARCHAR2 (50)  NOT NULL ,
    Teller_id     INTEGER  NOT NULL
)
;

ALTER TABLE Client
    ADD CONSTRAINT Client_PK PRIMARY KEY ( User_id ) ;

CREATE TABLE Document
(
    Document_id    INTEGER  NOT NULL ,
    File_name      VARCHAR2 (100)  NOT NULL ,
    File_extension VARCHAR2 (10)  NOT NULL ,
    File_data      BLOB  NOT NULL ,
    User_id        INTEGER  NOT NULL
)
;

ALTER TABLE Document
    ADD CONSTRAINT Document_PK PRIMARY KEY ( Document_id ) ;

CREATE TABLE Login_record
(
    Login_id         INTEGER  NOT NULL ,
    login_ip_address VARCHAR2 (20)  NOT NULL ,
    User_id          INTEGER  NOT NULL ,
    Login_time       DATE  NOT NULL
)
;

ALTER TABLE Login_record
    ADD CONSTRAINT Login_record_PK PRIMARY KEY ( Login_id ) ;

CREATE TABLE Message
(
    Message_id      INTEGER  NOT NULL ,
    Message_text    VARCHAR2 (1000)  NOT NULL ,
    Message_read    CHAR (1)  NOT NULL ,
    User_from_id    INTEGER ,
    Message_sent_at DATE  NOT NULL ,
    User_to_id      INTEGER  NOT NULL
)
;

ALTER TABLE Message
    ADD CONSTRAINT Message_PK PRIMARY KEY ( Message_id ) ;

CREATE TABLE Role
(
    Role_id          INTEGER  NOT NULL ,
    Role_name        VARCHAR2 (20)  NOT NULL ,
    Role_description VARCHAR2 (200)  NOT NULL
)
;

ALTER TABLE Role
    ADD CONSTRAINT Role_PK PRIMARY KEY ( Role_id ) ;

CREATE TABLE Teller
(
    User_id            INTEGER  NOT NULL ,
    Work_phone_number  VARCHAR2 (15)  NOT NULL ,
    Work_email_address VARCHAR2 (50)  NOT NULL ,
    Branch_id          INTEGER  NOT NULL
)
;

ALTER TABLE Teller
    ADD CONSTRAINT Teller_PK PRIMARY KEY ( User_id ) ;

CREATE TABLE Transaction
(
    Transaction_id        INTEGER  NOT NULL ,
    Transfer_amount       NUMBER  NOT NULL ,
    Message_for_sender    VARCHAR2 (200) ,
    Message_for_recipient VARCHAR2 (200) ,
    Account_from_id       INTEGER ,
    Transaction_type_id   INTEGER  NOT NULL ,
    Transaction_time      DATE  NOT NULL ,
    Account_to_id         INTEGER
)
;

ALTER TABLE Transaction
    ADD CONSTRAINT Transaction_PK PRIMARY KEY ( Transaction_id ) ;

CREATE TABLE Transaction_type
(
    Transaction_type_id          INTEGER  NOT NULL ,
    Transaction_type_name        VARCHAR2 (20)  NOT NULL ,
    Transaction_type_description VARCHAR2 (200)  NOT NULL
)
;

ALTER TABLE Transaction_type
    ADD CONSTRAINT Transaction_type_PK PRIMARY KEY ( Transaction_type_id ) ;

CREATE TABLE "User"
(
    User_id    INTEGER  NOT NULL ,
    Name       VARCHAR2 (50)  NOT NULL ,
    Surname    VARCHAR2 (50)  NOT NULL ,
    Password   VARCHAR2 (50)  NOT NULL ,
    active     CHAR (1)  NOT NULL ,
    approved   CHAR (1)  DEFAULT 'N' NOT NULL ,
    Role_id    INTEGER  NOT NULL ,
    Address_id INTEGER  NOT NULL
)
;

ALTER TABLE "User"
    ADD CONSTRAINT User_PK PRIMARY KEY ( User_id ) ;

ALTER TABLE Account
    ADD CONSTRAINT Account_Client_FK FOREIGN KEY
        (
         Client_id
            )
        REFERENCES Client
            (
             User_id
                )
;

ALTER TABLE Audit_log
    ADD CONSTRAINT Audit_log_User_FK FOREIGN KEY
        (
         User_id
            )
        REFERENCES "User"
            (
             User_id
                )
;

ALTER TABLE Branch
    ADD CONSTRAINT Branch_Address_FK FOREIGN KEY
        (
         Address_id
            )
        REFERENCES Address
            (
             Address_id
                )
;

ALTER TABLE Client
    ADD CONSTRAINT Client_Teller_FK FOREIGN KEY
        (
         Teller_id
            )
        REFERENCES Teller
            (
             User_id
                )
;

ALTER TABLE Client
    ADD CONSTRAINT Client_User_FK FOREIGN KEY
        (
         User_id
            )
        REFERENCES "User"
            (
             User_id
                )
;

ALTER TABLE Document
    ADD CONSTRAINT Document_User_FK FOREIGN KEY
        (
         User_id
            )
        REFERENCES "User"
            (
             User_id
                )
;

ALTER TABLE Login_record
    ADD CONSTRAINT Login_record_User_FK FOREIGN KEY
        (
         User_id
            )
        REFERENCES "User"
            (
             User_id
                )
;

ALTER TABLE Message
    ADD CONSTRAINT Message_User_FK FOREIGN KEY
        (
         User_from_id
            )
        REFERENCES "User"
            (
             User_id
                )
;

ALTER TABLE Message
    ADD CONSTRAINT Message_User_FKv1 FOREIGN KEY
        (
         User_to_id
            )
        REFERENCES "User"
            (
             User_id
                )
;

ALTER TABLE Teller
    ADD CONSTRAINT Teller_Branch_FK FOREIGN KEY
        (
         Branch_id
            )
        REFERENCES Branch
            (
             Branch_id
                )
;

ALTER TABLE Teller
    ADD CONSTRAINT Teller_User_FK FOREIGN KEY
        (
         User_id
            )
        REFERENCES "User"
            (
             User_id
                )
;

ALTER TABLE Transaction
    ADD CONSTRAINT Transaction_Account_FK FOREIGN KEY
        (
         Account_from_id
            )
        REFERENCES Account
            (
             Account_id
                )
;

ALTER TABLE Transaction
    ADD CONSTRAINT Transaction_Account_FKv1 FOREIGN KEY
        (
         Account_to_id
            )
        REFERENCES Account
            (
             Account_id
                )
;

ALTER TABLE Transaction
    ADD CONSTRAINT Transaction_type_FK FOREIGN KEY
        (
         Transaction_type_id
            )
        REFERENCES Transaction_type
            (
             Transaction_type_id
                )
;

ALTER TABLE "User"
    ADD CONSTRAINT User_Address_FK FOREIGN KEY
        (
         Address_id
            )
        REFERENCES Address
            (
             Address_id
                )
;

ALTER TABLE "User"
    ADD CONSTRAINT User_Role_FK FOREIGN KEY
        (
         Role_id
            )
        REFERENCES Role
            (
             Role_id
                )
;

COMMIT;



-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                            13
-- CREATE INDEX                             0
-- ALTER TABLE                             29
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   0
-- WARNINGS                                 0


-- 1) v_account_overview
